import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// The dev server proxies the API rather than calling http://localhost:8000
// directly. Two reasons, both practical: every fetch in `src/api.js` stays a
// relative path (so a production build served from the FastAPI app needs no
// rebuild), and recovery links generated by the backend — which point at
// localhost:8000 — keep working when clicked out of the activity feed.
//
// CORS is configured on the backend anyway for the case where someone points the
// dashboard at a remote instance with VITE_API_BASE.
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      '/api': 'http://localhost:8000',
      '/simulate': 'http://localhost:8000',
      '/healthz': 'http://localhost:8000',
    },
  },
  build: { outDir: 'dist', sourcemap: true },
})
